In [1]:
import numpy as np

1. Create a 2D Numpy array with shape (3, 3) containing random integers
between 1 and 20.

In [4]:
q1=np.random.randint(1,20,size=(3,3))
print(q1)

[[10 19 15]
 [ 5 16  2]
 [18  3 17]]


2. Write a NumPy program to create a 5x5 array with random values and find
the minimum and maximum values for each row.

In [55]:
q2= np.random.randint(0,100,size=(5,5))
print(f"{q2}\n")

min_row = np.min(q2, axis=1)
print(f"{min_row}\n")

max_row= np.max(q2, axis=1)
print(f"{max_row}\n")
#for row in q2 :
    

[[31 22 74 81 11]
 [ 9  0 77 14 35]
 [23 72 99 73 33]
 [77 93 12 37 95]
 [51 98 96 47 23]]

[11  0 23 12 23]

[81 77 99 95 98]



3. Write a NumPy program to create a random vector of size 10 and sort it.

In [ ]:
q3=np.random.randint(0,100,10)
print(f'original vector:{q3}\n')

q3.sort()
print(f'sorted vector:{q3}\n')

original vector:[71 36 40 74 83 86 59 43 96 24]

sorted vector:[24 36 40 43 59 71 74 83 86 96]



4. Write a NumPy program to find the most frequent value in an array.

In [19]:
q4=np.array([1,2,3,3,4,5,6])

print(np.bincount(q4).argmax())

3


5. Replace all even numbers in the 2D array with 0.

In [24]:
q5=np.array([[1,2,3,4,5],
           [6,7,8,9,10]])

q5[q5%2==0]=0
print(q5)


[[1 0 3 0 5]
 [0 7 0 9 0]]


6. Apply the square root function to each element of the 1D array.

In [56]:
import math
q=np.array([1,4,9,16,25,36])
q6=np.sqrt(q)
print(q6)

[1. 2. 3. 4. 5. 6.]


7. Write a NumPy program to create a 3x3 array with random values and
subtract the mean of each row from each element.

In [62]:
q=np.random.randint(0,100,size=(3,3))
print(q)

print(f'{q.mean(axis=1,keepdims=True)}\n')

q7=q-q.mean(axis=1,keepdims=True)
print(q7)

[[65 19 69]
 [68  4 62]
 [ 7 39 71]]
[[51.        ]
 [44.66666667]
 [39.        ]]

[[ 14.         -32.          18.        ]
 [ 23.33333333 -40.66666667  17.33333333]
 [-32.           0.          32.        ]]


8. Create a 1D array containing the first 20 odd numbers.

In [58]:
q8=np.arange(1,40,2)
q8

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39])

9. Write a NumPy program to create a 5x5 array with random values and find
the second-largest value in each column.

In [ ]:
q8=np.random.randint(0,100,size=(5,5))
print(f"{q8}\n")

max_col = np.max(q8, axis=0)
print(f"{max_col}\n")

min_s_col=np.partition(q8, -2, axis=0)[-2, :]

print(min_s_col)



[[93  2 75 79 58]
 [74 17 40 79 80]
 [15 33 73 49 45]
 [21 47 56 85 81]
 [82 20 89 28 38]]

[93 47 89 85 81]

[82 33 75 79 80]


10. Write a NumPy program to create a 4x4 array with random values and find
the sum of each row.

In [54]:
q10=np.random.randint(0,10,size=(4,4))
print(f'{q10}\n')

rows_sum=np.sum(q10,axis=1)

print(f'{rows_sum}\n')

[[2 4 8 9]
 [3 7 4 9]
 [5 9 7 5]
 [6 4 9 0]]

[23 23 26 19]

